### ISSUE TITLE
IPC - system V: semop

### ISSUE THREAD

**Issue by leskiw77** [Kotwic4/Sysopy-kolos2-drill#4]
:IPC - system V::Zaznacz prawdziwe zdania:
  a) Jezeli wywolujac funkcje semop bedziemy alokowac zasoby (wartosc sem_op ujemna) i jezeli ustawimy sygnalizator SEM_UNDO, to jezeli zasób nie zostanie zwolniony w ciagu zadanego przedzialu czasu, to jadro zwolni go automatycznie
> b) Jezeli wywolujac funkcje semop bedziemy alokowac zasoby (wartosc sem_op ujemna) i jezeli ustawimy sygnalizator SEM_UNDO, to jadro bedzie pamietac, ile zasobów zajelismy dla danego semafora i w momencie wykonania exit przez proces jadro sprawdzi, czy istnieja nie zastosowane wartosci nastawiajace dla tego semafora i w razie potrzeby dokona wyrównania wartosci semafora
> c) Funkcja semop realizuje w sposób atomowy operacje na zbiorze semaforów tzn. albo zostana wykonane wszystkie zadane operacje, albo zadna
> d) Operacja wykonywana przez funkcje semop moze zmienic stan co najwyzej jednego semafora ze zbioru
  e) Zadne z pozostalych zdan nie jest prawdziwe

BŁĄÐ: Operacja wykonywana przez funkcje semop moze zmienic stan co najwyzej jednego semafora ze zbioru. 
Z: http://upel.agh.edu.pl/wiet/mod/page/view.php?id=9612
Funkcja ta wykonuje operacje na zbiorze semaforów o identyfikatorze semid Liczba operacji do wykonania jest zdefiniowana w argumencie nsops Same operacje przekazywane w tablicy sops (zawierającej nsops elementów). Każda operacja zdefiniowana jest jako struktura postaci:

**Comment by Kotwic4** [comment]
Tutaj zależy jak interpretować słowo operacja. Moim zdaniem bezpiecznie jest zastosować terminologie że operacja to pojedyncza operacja zdefiniowana przez strukturę sembuf. Operacja wtedy może zmienić stań co najwyżej jednego semafora. Funkcja semop wykonuje atomowo zbiór operacji dzięki czemu wykonanie funkcji semop może zmienić na raz wartości paru semaforów.
